# Generated by Django 5.0.4 on 2024-05-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='other_grade_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='other_grade_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='other_grade_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='other_grade_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='other_grade_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
